In [1]:
import time 
import pandas as pd
apperance_table = pd.read_csv("data/appearances.csv")
apperance_table.head(100)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2222962_58051,2222962,58051,2477,61825,2012-07-13,Mykhaylo Kopolovets,UKR1,0,0,0,0,3
96,2222962_58150,2222962,58150,2477,55686,2012-07-13,Andriy Tkachuk,UKR1,1,0,0,0,90
97,2222962_58252,2222962,58252,4482,18105,2012-07-13,Sergiy Siminin,UKR1,0,0,0,0,90
98,2222962_58425,2222962,58425,2477,16247,2012-07-13,Igor Oshchypko,UKR1,0,0,0,0,90
99,2222962_58976,2222962,58976,4482,6994,2012-07-13,Maksim Startsev,UKR1,0,0,0,0,90

In [2]:
#reading 1st fact table (apperance)
apperance_table.drop(columns=["player_name"],inplace=True)
apperance_table.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,6646,2012-07-05,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,ELQ,0,0,0,1,90

In [3]:
#reading club dimension
club_dimension=pd.read_csv("data/clubs.csv")
club_dimension.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,SV Darmstadt 98,L1,NaN,27,25.6,13,48.1,1,Merck-Stadion am Böllenfalltor,17810,+€3.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,Ural Yekaterinburg,RU1,NaN,30,26.5,11,36.7,3,Yekaterinburg Arena,23000,+€880k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,30,26.5,15,50.0,8,Beşiktaş Park,42445,€-25.26m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,26.3,18,69.2,17,Olimpico di Roma,70634,€-76.90m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,30,25.4,21,70.0,19,Tottenham Hotspur Stadium,62850,€-120.05m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...

In [4]:
#reading competitions_dimension
competitions_dimension=pd.read_csv("data/competitions.csv")
competitions_dimension.drop(columns=["country_id"],inplace=True)
competitions_dimension.head()

,competition_id,competition_code,name,sub_type,type,country_name,domestic_league_code,confederation,url,is_major_national_league
0,CIT,italy-cup,italy-cup,domestic_cup,domestic_cup,Italy,IT1,europa,https://www.transfermarkt.co.uk/italy-cup/star...,False
1,NLSC,johan-cruijff-schaal,johan-cruijff-schaal,domestic_super_cup,other,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/johan-cruijff-...,False
2,GRP,kypello-elladas,kypello-elladas,domestic_cup,domestic_cup,Greece,GR1,europa,https://www.transfermarkt.co.uk/kypello-ellada...,False
3,POSU,supertaca-candido-de-oliveira,supertaca-candido-de-oliveira,domestic_super_cup,other,Portugal,PO1,europa,https://www.transfermarkt.co.uk/supertaca-cand...,False
4,RUSS,russian-super-cup,russian-super-cup,domestic_super_cup,other,Russia,RU1,europa,https://www.transfermarkt.co.uk/russian-super-...,False

In [5]:
#reading player_dimension
player_dimension=pd.read_csv("data/players.csv")
player_dimension.drop(columns=["current_club_domestic_competition_id"],inplace=True)
player_dimension.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,Attack,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,FC Bayern München,100000.0,3000000.0

In [6]:
#reading games_dimension
games_dimension=pd.read_csv("data/games.csv")
games_dimension.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2321027,L1,2013,1. Matchday,2013-08-11,33.0,41.0,3.0,3.0,8.0,...,Veltins-Arena,61973.0,Manuel Gräfe,https://www.transfermarkt.co.uk/fc-schalke-04_...,4-2-3-1,4-2-3-1,FC Schalke 04,Hamburger SV,3:3,domestic_league
1,2321033,L1,2013,1. Matchday,2013-08-10,23.0,86.0,0.0,1.0,13.0,...,EINTRACHT-Stadion,23000.0,Deniz Aytekin,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-3-1-2,Eintracht Braunschweig,Sportverein Werder Bremen von 1899,0:1,domestic_league
2,2321044,L1,2013,2. Matchday,2013-08-18,16.0,23.0,2.0,1.0,1.0,...,SIGNAL IDUNA PARK,80200.0,Peter Sippel,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,4-3-2-1,Borussia Dortmund,Eintracht Braunschweig,2:1,domestic_league
3,2321060,L1,2013,3. Matchday,2013-08-25,23.0,24.0,0.0,2.0,18.0,...,EINTRACHT-Stadion,23325.0,Wolfgang Stark,https://www.transfermarkt.co.uk/eintracht-brau...,4-3-2-1,4-2-3-1,Eintracht Braunschweig,Eintracht Frankfurt Fußball AG,0:2,domestic_league
4,2321072,L1,2013,5. Matchday,2013-09-14,16.0,41.0,6.0,2.0,1.0,...,SIGNAL IDUNA PARK,80645.0,Tobias Welz,https://www.transfermarkt.co.uk/borussia-dortm...,4-2-3-1,3-5-2,Borussia Dortmund,Hamburger SV,6:2,domestic_league

In [7]:
#transform club_dimension
club_dimension = pd.merge(club_dimension, competitions_dimension[['competition_id', 'name']].rename(columns={'name': 'competition_name'}),left_on='domestic_competition_id', right_on='competition_id',how="left")
club_dimension.drop(columns=["domestic_competition_id","competition_id"],inplace=True)
club_dimension.head()

,club_id,club_code,name,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url,competition_name
0,105,sv-darmstadt-98,SV Darmstadt 98,NaN,27,25.6,13,48.1,1,Merck-Stadion am Böllenfalltor,17810,+€3.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...,bundesliga
1,11127,ural-ekaterinburg,Ural Yekaterinburg,NaN,30,26.5,11,36.7,3,Yekaterinburg Arena,23000,+€880k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...,premier-liga
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,NaN,30,26.5,15,50.0,8,Beşiktaş Park,42445,€-25.26m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...,super-lig
3,12,as-rom,Associazione Sportiva Roma,NaN,26,26.3,18,69.2,17,Olimpico di Roma,70634,€-76.90m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...,serie-a
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,NaN,30,25.4,21,70.0,19,Tottenham Hotspur Stadium,62850,€-120.05m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...,premier-league

In [8]:
#transform player_dimension
player_dimension=pd.merge(player_dimension,club_dimension[["club_id","name"]].rename(columns={'name': 'club_name'}),left_on='current_club_id', right_on='club_id',how="left")
player_dimension.drop(columns=["current_club_id","club_id"],inplace=True)

In [9]:
#transform games_dimension
games_dimension=pd.merge(games_dimension,competitions_dimension[["competition_id","name"]].rename(columns={'name': 'competition_name'}),left_on="competition_id",right_on="competition_id",how="left")
games_dimension.drop(columns=["competition_id","home_club_id","away_club_id"],inplace=True)

In [10]:
#reading date dimension
date_dim=pd.read_csv("data/dimdates.csv")
date_dim.head()

,Id,Date,DateLongDescription,DateShortDescription,DayLongName,DayShortName,MonthLongName,MonthShortName,CalendarDay,CalendarWeek,...,FiscalDayInMonth,FiscalQuarter,FiscalQuarterStartDateId,FiscalQuarterEndDateId,FiscalNumberOfDaysInQuarter,FiscalDayInQuarter,FiscalYear,FiscalYearStartDateId,FiscalYearEndDateId,FiscalNumberOfDaysInYear
0,1,1960-01-01,"Friday, January 1, 1960","Jan 1, 1960",Friday,Fri,January,Jan,1,53,...,1,1,1,231,90,1,1960,1,1130,365
1,2,1960-01-02,"Saturday, January 2, 1960","Jan 2, 1960",Saturday,Sat,January,Jan,2,53,...,2,1,1,231,90,2,1960,1,1130,365
2,3,1960-01-03,"Sunday, January 3, 1960","Jan 3, 1960",Sunday,Sun,January,Jan,3,53,...,3,1,1,231,90,3,1960,1,1130,365
3,4,1960-01-04,"Monday, January 4, 1960","Jan 4, 1960",Monday,Mon,January,Jan,4,1,...,4,1,1,231,90,4,1960,1,1130,365
4,5,1960-01-05,"Tuesday, January 5, 1960","Jan 5, 1960",Tuesday,Tue,January,Jan,5,1,...,5,1,1,231,90,5,1960,1,1130,365

In [11]:
#adding date dimension to apperance fact
apperance_table=pd.merge(apperance_table,date_dim[["Id","Date"]].rename(columns={'Id': 'Date_id'}),left_on='date',right_on='Date',how="left")
apperance_table.drop(columns=["Date","date"],inplace=True   )
apperance_table.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,competition_id,yellow_cards,red_cards,goals,assists,minutes_played,Date_id
0,2231978_38004,2231978,38004,853,235,CLQ,0,0,2,0,90,520603
1,2233748_79232,2233748,79232,8841,2698,ELQ,0,0,0,0,90,520605
2,2234413_42792,2234413,42792,6251,465,ELQ,0,0,0,0,45,520605
3,2234418_73333,2234418,73333,1274,6646,ELQ,0,0,0,0,90,520605
4,2234421_122011,2234421,122011,195,3008,ELQ,0,0,0,1,90,520605

In [12]:
# reading transfer 2nd fact table
transfers_table = pd.read_csv("data/transfers.csv")
transfers_table.head()

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,16136,2026-07-01,26/27,417,123,OGC Nice,Retired,NaN,500000.0,Dante
1,195778,2026-06-30,25/26,79,27,VfB Stuttgart,Bayern Munich,0.0,12000000.0,Alexander Nübel
2,569033,2026-06-30,25/26,39,27,1.FSV Mainz 05,Bayern Munich,0.0,4000000.0,Armindo Sieb
3,626913,2026-06-30,25/26,398,380,Lazio,Salernitana,0.0,15000000.0,Boulaye Dia
4,887834,2026-06-30,25/26,979,1023,Moreirense,Palmeiras,0.0,1000000.0,Michel

In [13]:
# Transforming transfer table 
transfers_table.drop(columns=["player_name"],inplace=True)
transfers_table=pd.merge(transfers_table,date_dim[["Id","Date"]].rename(columns={'Id': 'Date_id'}),left_on="transfer_date",right_on="Date",how="left")
transfers_table.drop(columns=["Date","transfer_date"],inplace=True)
transfers_table.head()

,player_id,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,Date_id
0,16136,26/27,417,123,OGC Nice,Retired,NaN,500000.0,660601
1,195778,25/26,79,27,VfB Stuttgart,Bayern Munich,0.0,12000000.0,660530
2,569033,25/26,39,27,1.FSV Mainz 05,Bayern Munich,0.0,4000000.0,660530
3,626913,25/26,398,380,Lazio,Salernitana,0.0,15000000.0,660530
4,887834,25/26,979,1023,Moreirense,Palmeiras,0.0,1000000.0,660530

In [14]:
files=[apperance_table,transfers_table,club_dimension,games_dimension,player_dimension,competitions_dimension,date_dim]

In [15]:
import os
import pandas as pd
from hdfs import InsecureClient

# إنشاء عميل HDFS
client = InsecureClient('http://172.18.0.2:9870', user='root')
# مسار الإخراج في HDFS
hdfs_output_dir = '/hadoop_folder/transformed_data/csv_folder'

# قائمة الأسماء للملفات
file_names = [
    'apperance_table.csv',
    'transfers_table.csv',
    'club_dimension.csv',
    'games_dimension.csv',
    'player_dimension.csv',
    'competitions_dimension.csv',
    'date_dim.csv'
]

# التحقق من أن `files` موجودة وتحتوي على DataFrames بعدد مطابق لأسماء الملفات
if not isinstance(files, list) or len(files) != len(file_names):
    raise ValueError("تأكد من أن 'files' تحتوي على قائمة من DataFrames بنفس عدد أسماء الملفات")

# التأكد من أن جميع العناصر داخل `files` هي `DataFrame`
for i, df in enumerate(files):
    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"العنصر رقم {i} ({file_names[i]}) ليس DataFrame")

# حفظ الملفات في HDFS
start=time.time()   
for df, file_name in zip(files, file_names):
    hdfs_path = f"{hdfs_output_dir}/{file_name}"
    try:
        # تحويل DataFrame إلى CSV ورفعه مباشرة إلى HDFS
        with client.write(hdfs_path, encoding='utf-8', overwrite=True) as writer:
            df.to_csv(writer, index=False)

        print(f"✅ تم الحفظ في HDFS: {hdfs_path}")
    
    except Exception as e:
        print(f"❌ خطأ أثناء حفظ {file_name} في HDFS: {e}")
end=time.time()
elapsed_time = end - start
print(f'Uploaded to {hdfs_output_dir} csv in {elapsed_time:.2f} seconds')

✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/apperance_table.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/transfers_table.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/club_dimension.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/games_dimension.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/player_dimension.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/competitions_dimension.csv
✅ تم الحفظ في HDFS: /hadoop_folder/transformed_data/csv_folder/date_dim.csv
Uploaded to /hadoop_folder/transformed_data/csv_folder csv in 46.27 seconds

In [16]:
import fastavro
import pandas as pd
from hdfs import InsecureClient

# 🔹 تحديد مسار التخزين داخل HDFS
avro_output_dir = '/hadoop_folder/transformed_data/avro_folder/normal_avro'
client.makedirs(avro_output_dir)  # التأكد من وجود المجلد في HDFS

# 🔹 أسماء ملفات Avro
avro_file_names = [
    'apperance_table.avro',
    'transfers_table.avro',
    'club_dimension.avro',
    'games_dimension.avro',
    'player_dimension.avro',
    'competitions_dimension.avro',
    'date_dim.avro'
]
start=time.time()   

# 🔹 التأكد من أن الملفات تحتوي على DataFrames
files = [apperance_table, transfers_table, club_dimension, games_dimension, 
         player_dimension, competitions_dimension, date_dim]

# 🔹 تحويل القيم المفقودة والتأكد من التوافق مع Avro
for df, file_name in zip(files, avro_file_names):
    hdfs_path = f"{avro_output_dir}/{file_name}"  # تحديد المسار داخل HDFS

    # 🔸 1. استبدال NaN في البيانات النصية بـ "Unknown"
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].fillna("Unknown")

    # 🔸 2. تحويل الأعمدة المنطقية (Boolean) إلى عددية (0/1)
    for col in df.select_dtypes(include=['bool']).columns:
        df[col] = df[col].astype(int)

    # 🔸 3. معالجة الأعمدة الرقمية وتحويل القيم النصية إلى NaN
    for col in df.columns:
        if df[col].dtype == 'object':  
            df[col] = pd.to_numeric(df[col], errors='coerce')  # تحويل القيم الرقمية فقط
        if pd.api.types.is_numeric_dtype(df[col]):  
            df[col] = df[col].fillna(0)  # استبدال NaN بـ 0
            try:
                df[col] = df[col].astype('Int64')  # محاولة التحويل إلى Int64
            except:
                df[col] = df[col].astype('float64')  # إبقاء القيم كـ float إذا فشل التحويل

    # 🔸 4. إنشاء Schema لـ Avro مع دعم `null` للأعمدة الرقمية
    schema = {
        "type": "record",
        "name": "Record",
        "fields": [
            {"name": col, "type": ["null", "string"]} if df[col].dtype == "object"
            else {"name": col, "type": ["null", "long"]} if pd.api.types.is_integer_dtype(df[col])
            else {"name": col, "type": ["null", "double"]}
            for col in df.columns
        ]
    }

    # 🔸 5. حفظ البيانات كملف Avro داخل HDFS
    with client.write(hdfs_path, overwrite=True) as out_file:
        fastavro.writer(out_file, schema, df.to_dict(orient="records"))

    print(f"✅ Saved to HDFS: {hdfs_path}")
end=time.time()
elapsed_time = end - start
print(f'Uploaded to {avro_output_dir} normal_avro in {elapsed_time:.2f} seconds')

✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/apperance_table.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/transfers_table.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/club_dimension.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/games_dimension.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/player_dimension.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/competitions_dimension.avro
✅ Saved to HDFS: /hadoop_folder/transformed_data/avro_folder/normal_avro/date_dim.avro
Uploaded to /hadoop_folder/transformed_data/avro_folder/normal_avro normal_avro in 96.79 seconds

In [17]:
from hdfs import InsecureClient
import pyarrow as pa
import pyarrow.parquet as pq
import io

# تحديد مسار المجلد في HDFS
parquet_output_dir = '/hadoop_folder/transformed_data/parquet_folder/normal_parquet'
client.makedirs(parquet_output_dir)  # إنشاء المجلد إذا لم يكن موجودًا

# قائمة أسماء الملفات
parquet_file_names = [
    'apperance_table.parquet',
    'transfers_table.parquet',
    'club_dimension.parquet',
    'games_dimension.parquet',
    'player_dimension.parquet',
    'competitions_dimension.parquet',
    'date_dim.parquet'
]
start=time.time()   

# قائمة الـ DataFrames (تأكد أنها معرفة مسبقًا)
files = [apperance_table, transfers_table, club_dimension, games_dimension, player_dimension, competitions_dimension, date_dim]  # استبدل بـ DataFrames الحقيقية

# حفظ كل DataFrame كملف Parquet في HDFS
for df, file_name in zip(files, parquet_file_names):
    file_path = f"{parquet_output_dir}/{file_name}"  # مسار الملف في HDFS

    # تحويل DataFrame إلى Parquet داخل الذاكرة
    output_buffer = io.BytesIO()
    table = pa.Table.from_pandas(df)
    pq.write_table(table, output_buffer)

    # كتابة الملف إلى HDFS
    with client.write(file_path, overwrite=True) as hdfs_file:
        hdfs_file.write(output_buffer.getvalue())

    print(f"✅ Saved {file_path} to HDFS")
end=time.time()
elapsed_time = end - start
print(f'Uploaded to {parquet_output_dir} normal_avro in {elapsed_time:.2f} seconds')

✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/apperance_table.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/transfers_table.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/club_dimension.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/games_dimension.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/player_dimension.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/competitions_dimension.parquet to HDFS
✅ Saved /hadoop_folder/transformed_data/parquet_folder/normal_parquet/date_dim.parquet to HDFS
Uploaded to /hadoop_folder/transformed_data/parquet_folder/normal_parquet normal_avro in 1.21 seconds

In [18]:
from hdfs import InsecureClient
import fastavro
import io
import os
import time

# المسارات داخل HDFS
input_dir = "/hadoop_folder/transformed_data/avro_folder/normal_avro"
output_base_dir = "/hadoop_folder/transformed_data/avro_folder"

# أنواع الضغط المطلوبة
compression_types = ["snappy", "deflate", "zstandard"]

# التأكد من أن مجلدات الإخراج موجودة في HDFS
for codec in compression_types:
    client.makedirs(f"{output_base_dir}/{codec}")

# الحصول على قائمة ملفات Avro من HDFS
files = client.list(input_dir)

if not files:
    print("❌ لا توجد ملفات Avro في المجلد المحدد!")
else:
    write_times = {codec: [] for codec in compression_types}  # تخزين أوقات الكتابة لكل نوع ضغط

    for file_name in files:
        if file_name.endswith(".avro"):
            file_path = f"{input_dir}/{file_name}"

            try:
                # تحميل ملف Avro من HDFS
                with client.read(file_path) as reader:
                    avro_bytes = reader.read()

                # قراءة بيانات Avro إلى قائمة
                avro_buffer = io.BytesIO(avro_bytes)
                reader = fastavro.reader(avro_buffer)
                records = list(reader)
                schema = reader.writer_schema

                for codec in compression_types:
                    output_filename = f"{os.path.splitext(file_name)[0]}_{codec}.avro"
                    output_hdfs_path = f"{output_base_dir}/{codec}/{output_filename}"

                    # قياس وقت الكتابة
                    start_time = time.perf_counter()

                    # ضغط البيانات داخل الذاكرة
                    output_buffer = io.BytesIO()
                    fastavro.writer(output_buffer, schema, records, codec=codec)

                    # رفع الملف إلى HDFS
                    with client.write(output_hdfs_path, overwrite=True) as writer:
                        writer.write(output_buffer.getvalue())

                    end_time = time.perf_counter()
                    time_taken = end_time - start_time
                    write_times[codec].append(time_taken)

                    print(f"✅ تم ضغط {file_name} باستخدام {codec} ورفعه إلى {output_hdfs_path} ⏳ {time_taken:.4f} ثانية")

            except Exception as e:
                print(f"❌ خطأ أثناء معالجة {file_name}: {e}")

# حساب متوسط زمن الكتابة لكل نوع ضغط
print("\n📊 متوسط أوقات الكتابة لكل نوع ضغط:")
for codec, times in write_times.items():
    if times:
        avg_time = sum(times) / len(times)
        print(f"🗂 {codec}: متوسط {avg_time:.4f} ثانية ({len(times)} ملف)")
    else:
        print(f"⚠️ {codec}: لم يتم كتابة أي ملفات")

print("🎉 تم الانتهاء من ضغط جميع ملفات Avro ورفعها إلى HDFS!")

✅ تم ضغط apperance_table.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/apperance_table_snappy.avro ⏳ 48.3217 ثانية
✅ تم ضغط apperance_table.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/apperance_table_deflate.avro ⏳ 43.7141 ثانية
✅ تم ضغط apperance_table.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/apperance_table_zstandard.avro ⏳ 40.9776 ثانية
✅ تم ضغط club_dimension.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/club_dimension_snappy.avro ⏳ 0.0595 ثانية
✅ تم ضغط club_dimension.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/club_dimension_deflate.avro ⏳ 0.0598 ثانية
✅ تم ضغط club_dimension.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/club_dimension_zstandard.avro ⏳ 0.0614 ثانية
✅ تم ضغط competitions_dimension.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/competitions_dimension_snappy.avro ⏳ 0.0482 ثانية
✅ تم ضغط competitions_dimension.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/competitions_dimension_deflate.avro ⏳ 0.0429 ثانية
✅ تم ضغط competitions_dimension.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/competitions_dimension_zstandard.avro ⏳ 0.0379 ثانية
✅ تم ضغط date_dim.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/date_dim_snappy.avro ⏳ 2.8578 ثانية
✅ تم ضغط date_dim.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/date_dim_deflate.avro ⏳ 3.0055 ثانية
✅ تم ضغط date_dim.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/date_dim_zstandard.avro ⏳ 2.9866 ثانية
✅ تم ضغط games_dimension.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/games_dimension_snappy.avro ⏳ 3.0212 ثانية
✅ تم ضغط games_dimension.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/games_dimension_deflate.avro ⏳ 3.3994 ثانية
✅ تم ضغط games_dimension.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/games_dimension_zstandard.avro ⏳ 3.0993 ثانية
✅ تم ضغط player_dimension.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/player_dimension_snappy.avro ⏳ 1.3984 ثانية
✅ تم ضغط player_dimension.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/player_dimension_deflate.avro ⏳ 1.5704 ثانية
✅ تم ضغط player_dimension.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/player_dimension_zstandard.avro ⏳ 1.5080 ثانية
✅ تم ضغط transfers_table.avro باستخدام snappy ورفعه إلى /hadoop_folder/transformed_data/avro_folder/snappy/transfers_table_snappy.avro ⏳ 1.5191 ثانية
✅ تم ضغط transfers_table.avro باستخدام deflate ورفعه إلى /hadoop_folder/transformed_data/avro_folder/deflate/transfers_table_deflate.avro ⏳ 1.6687 ثانية
✅ تم ضغط transfers_table.avro باستخدام zstandard ورفعه إلى /hadoop_folder/transformed_data/avro_folder/zstandard/transfers_table_zstandard.avro ⏳ 1.5515 ثانية

📊 متوسط أوقات الكتابة لكل نوع ضغط:
🗂 snappy: متوسط 8.1751 ثانية (7 ملف)
🗂 deflate: متوسط 7.6372 ثانية (7 ملف)
🗂 zstandard: متوسط 7.1746 ثانية (7 ملف)
🎉 تم الانتهاء من ضغط جميع ملفات Avro ورفعها إلى HDFS!

In [19]:
from hdfs import InsecureClient
import pyarrow.parquet as pq
import io
import os
import time

# المسارات
input_dir = "/hadoop_folder/transformed_data/parquet_folder/normal_parquet"
output_base_dir = "/hadoop_folder/transformed_data/parquet_folder"

compression_types = ["snappy", "gzip", "brotli"]

# التأكد من أن مجلدات الإخراج موجودة في HDFS
for codec in compression_types:
    client.makedirs(f"{output_base_dir}/{codec}")

# الحصول على قائمة ملفات Parquet من HDFS
files = client.list(input_dir)

if not files:
    print("❌ لا توجد ملفات Parquet في المجلد المحدد!")
else:
    timing_results = {codec: [] for codec in compression_types}  # لتخزين أوقات الكتابة
    
    for file_name in files:
        file_path = f"{input_dir}/{file_name}"
        
        try:
            # تحميل ملف Parquet من HDFS
            with client.read(file_path) as reader:
                parquet_bytes = reader.read()
            
            # تحويل بيانات Parquet إلى PyArrow Table
            with io.BytesIO(parquet_bytes) as parquet_buffer:
                table = pq.read_table(parquet_buffer)

            for codec in compression_types:
                output_filename = f"{os.path.splitext(file_name)[0]}_{codec}.parquet"
                output_hdfs_path = f"{output_base_dir}/{codec}/{output_filename}"

                # تحويل البيانات إلى بايتات داخل الذاكرة
                output_buffer = io.BytesIO()
                
                start_time = time.perf_counter()  # بدء القياس
                pq.write_table(table, output_buffer, compression=codec)
                write_time = time.perf_counter() - start_time  # حساب الزمن
                
                # رفع الملف إلى HDFS
                with client.write(output_hdfs_path, overwrite=True) as writer:
                    writer.write(output_buffer.getvalue())

                timing_results[codec].append(write_time)
                
                print(f"✅ {file_name} -> {codec}: {write_time:.4f} ثانية")

        except Exception as e:
            print(f"❌ خطأ أثناء معالجة {file_name}: {e}")

    # طباعة ملخص الأوقات لكل نوع ضغط
    print("\n📊 ملخص أوقات الكتابة:")
    for codec, times in timing_results.items():
        avg_time = sum(times) / len(times) if times else 0
        print(f"🗜️ {codec}: متوسط وقت الكتابة {avg_time:.4f} ثانية")

print("🎉 تم الانتهاء من ضغط جميع الملفات ورفعها إلى HDFS!")

✅ apperance_table.parquet -> snappy: 0.4840 ثانية
✅ apperance_table.parquet -> gzip: 1.4870 ثانية
✅ apperance_table.parquet -> brotli: 1.8323 ثانية
✅ club_dimension.parquet -> snappy: 0.0027 ثانية
✅ club_dimension.parquet -> gzip: 0.0030 ثانية
✅ club_dimension.parquet -> brotli: 0.0027 ثانية
✅ competitions_dimension.parquet -> snappy: 0.0011 ثانية
✅ competitions_dimension.parquet -> gzip: 0.0037 ثانية
✅ competitions_dimension.parquet -> brotli: 0.0009 ثانية
✅ date_dim.parquet -> snappy: 0.0347 ثانية
✅ date_dim.parquet -> gzip: 0.0667 ثانية
✅ date_dim.parquet -> brotli: 0.0917 ثانية
✅ games_dimension.parquet -> snappy: 0.0392 ثانية
✅ games_dimension.parquet -> gzip: 0.1483 ثانية
✅ games_dimension.parquet -> brotli: 0.1575 ثانية
✅ player_dimension.parquet -> snappy: 0.0150 ثانية
✅ player_dimension.parquet -> gzip: 0.0390 ثانية
✅ player_dimension.parquet -> brotli: 0.0517 ثانية
✅ transfers_table.parquet -> snappy: 0.0186 ثانية
✅ transfers_table.parquet -> gzip: 0.0820 ثانية
✅ transfers_table.parquet -> brotli: 0.0617 ثانية

📊 ملخص أوقات الكتابة:
🗜️ snappy: متوسط وقت الكتابة 0.0850 ثانية
🗜️ gzip: متوسط وقت الكتابة 0.2614 ثانية
🗜️ brotli: متوسط وقت الكتابة 0.3141 ثانية
🎉 تم الانتهاء من ضغط جميع الملفات ورفعها إلى HDFS!

In [22]:
# قائمة المجلدات في HDFS التي نريد قياس وقت قراءتها
folders = [
    "/hadoop_folder/transformed_data/csv_folder",
    "/hadoop_folder/transformed_data/avro_folder/snappy",
    "/hadoop_folder/transformed_data/avro_folder/deflate",
    "/hadoop_folder/transformed_data/avro_folder/zstandard",
    "/hadoop_folder/transformed_data/parquet_folder/snappy",
    "/hadoop_folder/transformed_data/parquet_folder/gzip",
    "/hadoop_folder/transformed_data/parquet_folder/brotli"
]


# قياس وقت القراءة لكل مجلد
folder_times = {}

for folder_path in folders:
    start_time = time.perf_counter()  # بدء القياس
    try:
        files = client.list(folder_path)  # قراءة الملفات داخل المجلد
        end_time = time.perf_counter()  # إنهاء القياس

        time_taken = end_time - start_time
        folder_times[folder_path] = (len(files), time_taken)

        print(f"📂 {folder_path}: تم قراءة {len(files)} ملفًا في {time_taken:.4f} ثانية")
    
    except Exception as e:
        print(f"❌ خطأ أثناء قراءة {folder_path}: {e}")
        folder_times[folder_path] = (0, None)

📂 /hadoop_folder/transformed_data/csv_folder: تم قراءة 7 ملفًا في 0.0167 ثانية
📂 /hadoop_folder/transformed_data/avro_folder/snappy: تم قراءة 7 ملفًا في 0.0090 ثانية
📂 /hadoop_folder/transformed_data/avro_folder/deflate: تم قراءة 7 ملفًا في 0.0092 ثانية
📂 /hadoop_folder/transformed_data/avro_folder/zstandard: تم قراءة 7 ملفًا في 0.0073 ثانية
📂 /hadoop_folder/transformed_data/parquet_folder/snappy: تم قراءة 7 ملفًا في 0.0065 ثانية
📂 /hadoop_folder/transformed_data/parquet_folder/gzip: تم قراءة 7 ملفًا في 0.0052 ثانية
📂 /hadoop_folder/transformed_data/parquet_folder/brotli: تم قراءة 7 ملفًا في 0.0054 ثانية